### ISSUE TITLE
Novice problems running demo

### ISSUE THREAD

**Issue by kevinsullivan** [lukexi/halive#9]
The live coding and diagramming packages look interesting. Not being a Haskell person I could use a hand trying out your live coding system. My first step was to clone your repo. Then using "stack" (rather than "cabal install") I did "stack build." That command downloaded dependencies and built your halive executable. But I'm not able to successfully run the demo. When I type "halive demo/Main.hs" I get a bunch of "could not find module" errors for the included modules. Clearly the compiler's not looking in the right places for the required modules. I know this is my fault for not being a haskell programmer, and it probably has something to do with using stack (https://github.com/commercialhaskell/stack). By the way, the error messages about modules not being found come with a bunch of unprintable characters.

I'm running on an Ubuntu box. If you can advise on how I should modify the command line to point to the required Haskell modules/libraries, and also will I need to install libraries on my OS?

**Comment by lukexi** [comment]
Hi Kevin!

Hm, I haven't tried to use it with stack yet as I built this before I myself switched to stack : ).

Besides that though — the readme mentions that the demo depends on "gl, GLFW-b, foreign-store, linear, and random" which could be clearer for beginners! What I mean to say there is that you should do
`cabal install gl GLFW-b foreign-store linear random` before trying to run the test (or 'stack install', but again, I'm not sure if that will work because I haven't added explicit stack support yet).

Please let me know how you get on! 
(and I'm definitely planning on adding stack support very soon!)

Oh, and regarding the unprintable characters, do they happen if you do `runhaskell demo/Main.hs` too?

**Comment by lukexi** [comment]
Howdy, there have been some changes that should make things easier for you if ya happen to try this again — if you do a `cd where-you-cloned-halive && git pull && stack install && stack build --test --no-run-tests` you should be able to run `halive demo/Main.hs` smoothly now! I've been using it exclusively with `stack` myself now that I've added support. I'll close this for now but feel free to reopen if you run into issues!
